name: this is a github action
run-name: This is the run name
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: sleep 1m && echo test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: sleep 2m && echo build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deploy
